### ISSUE TITLE
Card age is not showing on all lists even after refresh (tested on Brave)

### ISSUE THREAD

**Issue by Mauro-Oliveira** [derrickqin/true-card-age-for-trello#1]
![image](https://user-images.githubusercontent.com/10239756/77709364-b1fad100-702f-11ea-97c3-540d0c031ce2.png)

**Comment by Mauro-Oliveira** [comment]
by the way, It will eventually show the age after several refreshes and Ctrl+F5 appears to force the age to be displayed.

**Comment by derrickqin** [comment]
Hey @Mauro-Oliveira, thanks for reporting this issue.

I also experienced the same issue lately. Looks like Trello has restricted the number of concurrent API calls.
For small Trello board, this extension works okay, but for the Trello boards which have many cards (>20), some of the calls will fail. This results on the card aging feature not working.

I'm currently working on a fix to delay or batch the calls. In the meantime, I recommend you to move/archive your done cards to keep your board small.

I'll update again once I have a proper fix.

Thanks!
Derrick

**Comment by derrickqin** [comment]
@Mauro-Oliveira Not sure if you are still using this extension but I released a version that should fix this issue because it will check if aging label is added. If not, it will do it again. Thanks!
